spring:
  datasource:
    data-username: root
    data-password: root
    url: jdbc:mysql:localhost:8080/ss?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp